BUG: Change signature of qSlicerModuleFactoryManagerTest1 main
To fix the following error:
error LNK2001: unresolved external symbol "int __cdecl qSlicerModuleFactoryManagerTest1(int,char * * const)

Changed from
  myTest(int argc, char ** argv)
to
  myTest(int argc, char* argv[])

git-svn-id: http://svn.slicer.org/Slicer3/trunk@13658 3bd1e089-480b-0410-8dfb-8563597acbee